#!/usr/bin/env ruby

require "bundler/setup"
require "server_console/agent"

# Get data
results = ''
$stdin.each do |line|
  results << line
end

# Load config
ServerConsole::Agent.message(ARGV[0], results)
